version: '3.6'

services:
  db:
    container_name: acme_db
    image: mongo
    networks:
    - acme-backend
  acme_api:
    container_name: acme_api
    image: maven:3.5.2-jdk-8
    depends_on:
    - db
    ports:
    - 8080:8080
    volumes:
    - ./:/app
    working_dir: /app
    command:
    - ./docker/start.sh
    networks:
    - acme-backend
networks:
  acme-backend: